### PR TITLE
Ability to use AssertNotEmitted when no events are present

### LINKED ISSUE #1673: Undefined index: emits in ->assertEmitted()
### Description
Assert Emitted throws an undefined Index error

### Exact steps to reproduce
Attempt to test a Livewire component that emits an event

### Stripped-down, copy-pastable code snippets
Livewire::test(Car::class)
            ->set('registration', "XXXXXXXX")
            ->call('render')
            ->assertSet('make', 'Toyota')
            ->assertSet('year', '2010')
            ->assertEmitted('car');

**Context**

- Laravel Framework 7.28.2
- Livewire version: 2.2.6
- Browser: Chrome

### PR DESCRIPTION
**Pull request by ahinkle**
1️⃣ Is this something that is wanted/needed? Did you create an issue / discussion about it first?
Closes #1673 

2️⃣ Does it contain multiple, unrelated changes? Please separate the PRs out.
Nope

3️⃣ Does it include tests, if possible? (Not a deal-breaker, just a nice-to-have)
Yes, includes tests.

4️⃣ Please include a thorough description of the improvement and reasons why it's useful.
Currently, it's not possible to use `assertNotEmitted()` when no emits were fired at all on the component.

Returns: `ErrorException: Undefined index: emits`.

This PR allows the ability for `assertNotEmitted()` to be called when no emits at all were fired on the component.

Real world example:
```php
public function test_updating_only_state_doesnt_fire_shipping_methods_event()
{
    Livewire::test(EstimateShippingAndTax::class)
        ->set('state', 'AL');
        ->assertNotEmitted('refreshShippingMethods'); // ErrorException: Undefined index: emits
}

public function test_updating_only_zip_doesnt_fire_shipping_methods_event()
{
    Livewire::test(EstimateShippingAndTax::class)
        ->set('zip', '00001');
        ->assertNotEmitted('refreshShippingMethods'); // ErrorException: Undefined index: emits
}

public function test_updating_zip_and_state_fires_shipping_method_event()
{
    Livewire::test(EstimateShippingAndTax::class)
        ->set('state', 'AL')
        ->set('zip', '00001')
        ->assertEmitted('refreshShippingMethods');
}
```
5️⃣ Thanks for contributing! 🙌

### CODE REVIEW

**Comment by zepfietje** [comment]
LGTM. Wanted to implement a fix for https://github.com/livewire/livewire/issues/1673, but then found this PR ready to be merged.

@ahinkle, could you link that issue (https://github.com/livewire/livewire/issues/1673) to this PR for others encountering it?
Maybe also rebase onto master to fix failing tests.

@calebporzio, would be nice if this gets merged ASAP; this bug makes testing quite hard ATM.

**Comment by ahinkle** [comment]
@zepfietje Done, thanks! However, looks like some unrelated tests are still failing from master.

File: src/Testing/Concerns/MakesAssertions.php [hunk 1]
```diff
@@ -139,15 +139,15 @@ protected function testEmitted($value, $params)
         $assertionSuffix = '.';
 
         if (empty($params)) {
-            $test = collect($this->payload['effects']['emits'])->contains('event', '=', $value);
+            $test = collect($this->payload['effects']['emits'] ?? [])->contains('event', '=', $value);
```
Comment (nuernbergerA) [inline src/Testing/Concerns/MakesAssertions.php:142]: `Collection` accepts also null, so i would pull stuff from a neasted-array like this `collect(data_get($this->payload, 'effects.emits'))`

applies for all appearances in this file

File: tests/Unit/LivewireTestingTest.php [hunk 2]
```diff
@@ -218,6 +220,11 @@ public function emitFoo()
         $this->emit('foo');
     }
 
+    public function methodWithoutEmit()
```
Comment (nuernbergerA) [inline tests/Unit/LivewireTestingTest.php:223]: I don't think it's necessary to call a function that does nothing

File: tests/Unit/LivewireTestingTest.php [hunk 3]
```diff
@@ -106,6 +106,8 @@ public function assert_not_emitted()
     {
         app(LivewireManager::class)
             ->test(EmitsEventsComponentStub::class)
+            ->call('methodWithoutEmit')
```
Comment (nuernbergerA) [inline tests/Unit/LivewireTestingTest.php:109]: remove call and just assert that nothing was emitted

File: src/Testing/Concerns/MakesAssertions.php (hunk 1 above)
Comment (ahinkle) [reply src/Testing/Concerns/MakesAssertions.php]: Hot tip.. thanks

**Comment by calebporzio** [comment]
Thanks! Good fix!
