### PR TITLE
fix vapor condition

### LINKED ISSUE #520: The /tmp/storage/bootstrap/cache directory must be present and writable.
**Describe the bug**

#385 broke our app:

```
The /tmp/storage/bootstrap/cache directory must be present and writable. 
```

We reverted back to v0.5.2 and it's working just fine.

**Additional context**

It doesn't work with `livewire.manifest_path` set to `null` or not set at all.

The manifest path seems to evaluate to `/app/bootstrap/cache/livewire-components.php`.

### PR DESCRIPTION
**Pull request by tillkruss**
Fixes #520, which was introduced in v0.5.3 via #385.

### CODE REVIEW

File: src/LivewireServiceProvider.php [hunk 1]
```diff
@@ -51,14 +51,15 @@ public function register()
         $this->app->singleton('livewire', LivewireManager::class);
 
         $this->app->singleton(LivewireComponentsFinder::class, function () {
-            $isHostedOnVapor = $_ENV['SERVER_SOFTWARE'] ?? null === 'vapor';
+            $isHostedOnVapor = ($_ENV['SERVER_SOFTWARE'] ?? null) === 'vapor';
+
```
Comment (tillkruss) [inline src/LivewireServiceProvider.php]: @calebporzio: You should tweet this change to educate the people 😉

**Comment by calebporzio** [comment]
Thanks @tillkruss!
